# Numpy

In [7]:
import numpy as np
a = [1,2,3,4]
b = [5,6,7,8]
a1 = np.array(a)
b1 = np.array(b)

In [8]:
c1 = a1 * b1

In [9]:
c1

array([ 5, 12, 21, 32])

In [11]:
a1 + b1

array([ 6,  8, 10, 12])

In [12]:
a1 / b1

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [15]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [16]:
np.array(x)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

arange

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
l1 = [1,2.5,5]
np.array(l1)

array([1. , 2.5, 5. ])

linspace

In [18]:
np.linspace(0,13,3)

array([ 0. ,  6.5, 13. ])

In [19]:
np.linspace(0,25,7)

array([ 0.        ,  4.16666667,  8.33333333, 12.5       , 16.66666667,
       20.83333333, 25.        ])

eye

In [22]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

reshape

In [29]:
l = np.arange(1,51)
l.reshape(5,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [25]:
np.eye(4,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

random

In [31]:
np.random.randint(1,100,20)

array([44,  5, 66, 17, 21, 16, 31, 99,  5, 46, 84,  9,  9, 24, 92, 12, 20,
       46,  4, 85])

In [32]:
np.random.randint(1,100,20).reshape(5,4)

array([[27, 10, 25, 77],
       [46,  8, 13, 32],
       [40, 61, 50, 50],
       [42, 68, 26, 44],
       [21, 10, 29, 11]])

In [33]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr[0,0]

1

In [36]:
arr[:,0]

array([1, 4, 7])

In [37]:
arr[0:2,1]

array([2, 5])

In [38]:
arr > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [47]:
arr[(arr > 3) & (arr < 7)]

array([4, 5, 6])

In [48]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
a = np.ones(10)
a * 5 

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [53]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [54]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [57]:
l = np.arange(0,9)
l.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
np.random.rand()

0.49366075575558943

In [70]:
l = np.arange(0.01,1.01,0.01)
l.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [71]:
l = np.arange(1,101)
l1 = l /100

In [72]:
l1.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [73]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [74]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [75]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [76]:
mat[3,4]

20

In [86]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [82]:
mat[4]

array([21, 22, 23, 24, 25])

In [83]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [84]:
mat.sum()

325

In [85]:
mat.std()

7.211102550927978

In [94]:
mat[:,0:1]

55

In [97]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])